### ISSUE TITLE
Data(preprocessing)

### ISSUE THREAD

**Issue by ricobruland** [dfsbora/latex-math-model#7]
Source more data and implement preprocessing.

**Comment by dfsbora** [comment]
Basic preprocessing generates a single file data.tex clean of comments, empty lines, chapter formatting, and filtered content.

**Comment by dfsbora** [comment]
- Uses eos tag as a separator for meaningful blocks  (e.g. keeps a proof environment as a whole thing).
- Updated data.tex and also created a smaller data from two short chapters for quicker tests (data_small.tex) 
- Evaluated size of a meaningful blocks (Mean: 162; Median: 123)

**Comment by dfsbora** [comment]
Proposal to use plain text was rejected.
